[package]
name = "KrysalisNative"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
winit = { version = "0.29", features = ["rwh_06"] }
nalgebra = "0.33"

[lib]
crate-type = ["cdylib"]

