[workspace]
members = [
    "KrysalisNativeFFI",
    "KrysalisNativeWrapper",
    "KrysalisNativeAPI",
    "KrysalisRenderer",
    "KrysalisHAL",
    "KrysalisNativeTestApplication",
    "KrysalisNativeTestRunner"
]
