[package]
name = "KrysalisNativeTests"
version = "0.1.0"
edition = "2021"

[dependencies]
KrysalisNative = { path = "../KrysalisNative" }

[[test]]
name = "KrysalisNativeTests"
path = "src/main.rs"
harness = false