name: Build DLLs

# Trigger the workflow on push to main branch and on pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    name: Build Solution
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download Filament library
      - name: Download Filament Library
        run: |
          New-Item -ItemType Directory -Path "C:/Libraries/filament-windows/" -Force
          Invoke-WebRequest -Uri "https://github.com/google/filament/releases/download/v1.55.0/filament-v1.55.0-windows.tgz" -OutFile "filament.tgz"
          tar -xzf filament.tgz -C C:/Libraries/filament-windows/
        
      # Setup Visual Studio Build Tools
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1

      - name: Install dependencies
        run: nuget restore Krysalis.sln

      # Build the solution
      - name: Build the solution
        run: msbuild Krysalis.sln /p:Configuration=Release /p:Platform=x64 /p:AdditionalOptions="/std:c++20"
      
      # Upload DLLs as build artifacts
      - name: Upload DLLs as build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-dlls
          path: |
            **/x64/Release/KrysalisNative.dll
            **/x64/Release/KrysalisManaged.dll
