name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, Test, and Release
    strategy:
      matrix:
        os: [windows-2022-gpu-t4-4-core]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Cache Rust dependencies and intermediate files
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo
      #       target
      #     key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      #     restore-keys: |
      #       cargo-${{ runner.os }}-

      # - name: Cache .NET dependencies and intermediate files
      #   if: runner.os == 'windows-latest' || runner.os == 'ubuntu-latest'
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.nuget/packages
      #     key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
      #     restore-keys: |
      #       nuget-${{ runner.os }}-

      - name: Cache Vulkan SDK
        id: cache-vulkan-sdk
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/VulkanSDK
          key: vulkan-sdk-${{ runner.os }}-1.3.283.0
          restore-keys: |
            vulkan-sdk-${{ runner.os }}-
            vulkan-sdk-

      - name: Setup Vulkan
        run: |
            Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanSDK-1.3.296.0-Installer.exe" -OutFile VulkanSDK.exe
            $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
            $installer.WaitForExit();

      - name: Set Vulkan SDK Environment Variables
        shell: powershell
        run: |
          $env:VULKAN_SDK = "C:\VulkanSDK\1.2.198.0"
          $env:PATH = "$env:VULKAN_SDK\Bin;$env:PATH"
          $env:LD_LIBRARY_PATH = "$env:VULKAN_SDK\Lib;$env:LD_LIBRARY_PATH"

      - name: Run Python build script
        shell: pwsh
        run: |
          python -u Krysalis.py

      - name: Run tests
        shell: pwsh
        run: |
          dotnet run --project KrysalisManagedTests/KrysalisManagedTests.csproj

      - name: Prepare artifact structure (Windows)
        if: matrix.os == 'windows-2022-large'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path artifact/Krysalis -Force
          Copy-Item KrysalisManaged/bin/Release/netstandard2.0/KrysalisManaged.dll artifact/Krysalis/KrysalisManaged.dll
          Copy-Item target/release/KrysalisNative.dll artifact/Krysalis/KrysalisNative.dll
          Copy-Item Krysalis/bin/Release/netstandard2.0/Krysalis.dll artifact/Krysalis.dll
          Compress-Archive -Path "artifact/Krysalis.dll", "artifact/Krysalis" -DestinationPath "Krysalis-Windows-v${{ github.run_number }}.zip"

      - name: Prepare artifact structure (Linux)
        if: matrix.os == 'ubuntu-20.04-large'
        run: |
          mkdir -p artifact/Krysalis
          cp KrysalisManaged/bin/Release/netstandard2.0/KrysalisManaged.dll artifact/Krysalis/KrysalisManaged.dll
          cp target/release/libKrysalisNative.so artifact/Krysalis/libKrysalisNative.so
          cp Krysalis/bin/Release/netstandard2.0/Krysalis.dll artifact/Krysalis.dll
          cd artifact
          zip -r "../Krysalis-Linux-v${{ github.run_number }}.zip" ./*
        shell: bash

      - name: Prepare artifact structure (macOS)
        if: matrix.os == 'macos-12-large'
        run: |
          mkdir -p artifact/Krysalis
          cp KrysalisManaged/bin/Release/netstandard2.0/KrysalisManaged.dll artifact/Krysalis/KrysalisManaged.dll
          cp target/release/libKrysalisNative.dylib artifact/Krysalis/libKrysalisNative.dylib
          cp Krysalis/bin/Release/netstandard2.0/Krysalis.dll artifact/Krysalis.dll
          cd artifact
          zip -r "../Krysalis-macOS-v${{ github.run_number }}.zip" ./*
        shell: bash

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-2022-large'
        uses: actions/upload-artifact@v3
        with:
          name: Krysalis-Windows
          path: Krysalis-Windows-v${{ github.run_number }}.zip

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-20.04-large'
        uses: actions/upload-artifact@v3
        with:
          name: Krysalis-Linux
          path: Krysalis-Linux-v${{ github.run_number }}.zip

      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-12-large'
        uses: actions/upload-artifact@v3
        with:
          name: Krysalis-macOS
          path: Krysalis-macOS-v${{ github.run_number }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: Krysalis-Windows
          path: artifacts/windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: Krysalis-Linux
          path: artifacts/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: Krysalis-macOS
          path: artifacts/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows/Krysalis-Windows-v${{ github.run_number }}.zip
            artifacts/linux/Krysalis-Linux-v${{ github.run_number }}.zip
            artifacts/macos/Krysalis-macOS-v${{ github.run_number }}.zip
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
